# Generated by Django 4.0.1 on 2022-01-27 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Dt. de envio')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('finished', 'Finalizada')], default='open', max_length=20, verbose_name='Situação')),
                ('total_correct', models.PositiveIntegerField(default=0, verbose_name='Total de acertos')),
                ('total_erros', models.PositiveIntegerField(default=0, verbose_name='Total de erros')),
                ('percentage_correct', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Aproveitamento')),
            ],
            options={
                'verbose_name': 'Resposta do Exame',
                'verbose_name_plural': 'Respostas dos Exames',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('update_at', models.DateTimeField(auto_now=True, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('active', 'Ativo')], default='open', max_length=20, verbose_name='Situação')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Título')),
                ('is_single_choice', models.BooleanField(default=True, verbose_name='É de escolha única?')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='academic.exam', verbose_name='Exame')),
            ],
            options={
                'verbose_name': 'Questão do exame',
                'verbose_name_plural': 'Questões dos exames',
            },
        ),
        migrations.CreateModel(
            name='ExamQuestionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Texto da opção')),
                ('is_correct', models.BooleanField(default=False, verbose_name='É uma opção correta?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='academic.examquestion', verbose_name='Questão')),
            ],
            options={
                'verbose_name': 'Opção de questão de exame',
                'verbose_name_plural': 'Opções de questões de exames',
            },
        ),
        migrations.CreateModel(
            name='AnswerExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='A resposta está correta?')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersquestions', to='academic.answerexame', verbose_name='Resposta do exame')),
                ('options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersquestions', to='academic.examquestionoption', verbose_name='Opção da questão do exame')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answersquestions', to='academic.examquestion', verbose_name='Resposta da questão do exame')),
            ],
            options={
                'verbose_name': 'Resposta de questão do Exame',
                'verbose_name_plural': 'Respostas de questões de avaliações dos cursos',
            },
        ),
        migrations.AddField(
            model_name='answerexame',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='academic.exam'),
        ),
        migrations.AddField(
            model_name='answerexame',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
