# Generated by Django 4.0.1 on 2022-01-27 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_alter_answerexame_exam_alter_exam_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerexame',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='academic.exam'),
        ),
        migrations.AlterField(
            model_name='answerexame',
            name='percentage_correct',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Aproveitamento'),
        ),
    ]
